version: '3.7'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/data:/var/lib/mysql
    ports:
      - 3306:3306
