version: '3.7'
services:
  node:
    image: node:latest
    working_dir: /app
    tty: true
    volumes:
      - .:/app

  db:
    image: postgres:14.2

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blog_db

    volumes:
      - ./db:/var/lib/postgresql/data

    ports:
      - '5432:5432'
