version: '3.7'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipe_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: UTC
    ports:
      - 3306:3306
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  db-store:
